### PR TITLE
Remove external dependency on QQMusicCommon.dll

### PR DESCRIPTION
**Pull request by wangqr**
To make it easier to build for other platforms (win64, macOS, etc)

### CODE REVIEW

**Comment by SuJiKiNen** [comment]
Great work!
Would mind make some changes?
* handle memory allocation failure, which I didn't do before(eg. OOM)
* put DES related files to a folder
* switch to cmake.
* add build guide.
* add tests

the last one may be a little overwhelmed for such a small project.
if you don't want change, I'm ok with that,I'm gonna merged it anyway,
thanks for your time.

**Comment by SuJiKiNen** [comment]
Some other thoughts,actually it was hard to distribute such an plugin for user.
Maybe an pure Lua implementation would be better,but it need more works.
what's your opinion?

**Comment by wangqr** [comment]
> handle memory allocation failure, which I didn't do before(eg. OOM)

I'm not sure what can we do if OOM, other than just return nullptr. I do see some problem here with the usage of zlib, by allocating output buffer with magic size (input size *100 for krc and *16 for qrc) and does not handle the error if buffer too small. Should I rewrite that part (ideally with the recommended `inflate` API of zlib instead of `uncompress`)?

**Comment by SuJiKiNen** [comment]
>  I do see some problem here with the usage of zlib, by allocating output buffer with magic size (input size *100 for krc and *16 for qrc) and does not handle the error if buffer too small. Should I rewrite that part (ideally with the recommended `inflate` API of zlib instead of `uncompress`)?

sure,after that I will test all of this and merge it.

**Pull request merged**
